services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: DB_HOST
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: DB_NAME
      - key: DB_USERNAME
        value: DB_USER
      - key: DB_PASSWORD
        value: DB_PASSWORD
